CREATE TABLE IF NOT EXISTS google_ads_accounts (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  manager_id TEXT NOT NULL DEFAULT '',
  manager_name TEXT NOT NULL DEFAULT '',
  currency TEXT NOT NULL DEFAULT 'BRL',
  status TEXT NOT NULL DEFAULT 'Ativa',
  balance NUMERIC NOT NULL DEFAULT 0,
  cost NUMERIC NOT NULL DEFAULT 0,
  impressions BIGINT NOT NULL DEFAULT 0,
  clicks BIGINT NOT NULL DEFAULT 0,
  conversions BIGINT NOT NULL DEFAULT 0,
  cpc NUMERIC NOT NULL DEFAULT 0
);

ALTER TABLE google_ads_accounts DISABLE ROW LEVEL SECURITY;
